[2025-03-27 02:51:49 -0300] [32095] [INFO] Starting gunicorn 23.0.0
[2025-03-27 02:51:49 -0300] [32095] [INFO] Listening at: http://0.0.0.0:5049 (32095)
[2025-03-27 02:51:49 -0300] [32095] [INFO] Using worker: sync
[2025-03-27 02:51:49 -0300] [32096] [INFO] Booting worker with pid: 32096
[2025-03-27 02:51:50 -0300] [32097] [INFO] Booting worker with pid: 32097
[2025-03-27 02:51:50 -0300] [32098] [INFO] Booting worker with pid: 32098
[2025-03-27 02:51:50 -0300] [32099] [INFO] Booting worker with pid: 32099
[2025-03-27 02:51:50 -0300] [32096] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
    ~~~~~~~~~~~~~~^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ~~~~~~~~~~~~~^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ~~~~~~~~~^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ~~~~~~~~~~~~~~~~~^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/kalicat/Desktop/inventory_website/app.py", line 4, in <module>
    from database import db, Item, User, ApiKey
ImportError: cannot import name 'ApiKey' from 'database' (/home/kalicat/Desktop/inventory_website/database.py)
[2025-03-27 02:51:50 -0300] [32096] [INFO] Worker exiting (pid: 32096)
[2025-03-27 02:51:50 -0300] [32095] [ERROR] Worker (pid:32096) exited with code 3
[2025-03-27 02:51:50 -0300] [32097] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
    ~~~~~~~~~~~~~~^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ~~~~~~~~~~~~~^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ~~~~~~~~~^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ~~~~~~~~~~~~~~~~~^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/kalicat/Desktop/inventory_website/app.py", line 4, in <module>
    from database import db, Item, User, ApiKey
ImportError: cannot import name 'ApiKey' from 'database' (/home/kalicat/Desktop/inventory_website/database.py)
[2025-03-27 02:51:50 -0300] [32097] [INFO] Worker exiting (pid: 32097)
[2025-03-27 02:51:50 -0300] [32098] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
    ~~~~~~~~~~~~~~^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ~~~~~~~~~~~~~^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ~~~~~~~~~^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ~~~~~~~~~~~~~~~~~^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/kalicat/Desktop/inventory_website/app.py", line 4, in <module>
    from database import db, Item, User, ApiKey
ImportError: cannot import name 'ApiKey' from 'database' (/home/kalicat/Desktop/inventory_website/database.py)
[2025-03-27 02:51:50 -0300] [32098] [INFO] Worker exiting (pid: 32098)
[2025-03-27 02:51:51 -0300] [32099] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
    ~~~~~~~~~~~~~~^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ~~~~~~~~~~~~~^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ~~~~~~~~~^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ~~~~~~~~~~~~~~~~~^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/kalicat/Desktop/inventory_website/app.py", line 4, in <module>
    from database import db, Item, User, ApiKey
ImportError: cannot import name 'ApiKey' from 'database' (/home/kalicat/Desktop/inventory_website/database.py)
[2025-03-27 02:51:51 -0300] [32099] [INFO] Worker exiting (pid: 32099)
[2025-03-27 02:51:51 -0300] [32095] [ERROR] Worker (pid:32097) exited with code 3
Traceback (most recent call last):
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/arbiter.py", line 208, in run
    self.sleep()
    ~~~~~~~~~~^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/arbiter.py", line 359, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/arbiter.py", line 241, in handle_chld
    self.reap_workers()
    ~~~~~~~~~~~~~~~~~^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/arbiter.py", line 529, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/bin/gunicorn", line 8, in <module>
    sys.exit(run())
             ~~~^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 66, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]", prog=prog).run()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/app/base.py", line 235, in run
    super().run()
    ~~~~~~~~~~~^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/app/base.py", line 71, in run
    Arbiter(self).run()
    ~~~~~~~~~~~~~~~~~^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/arbiter.py", line 228, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/arbiter.py", line 341, in halt
    self.stop()
    ~~~~~~~~~^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/arbiter.py", line 395, in stop
    time.sleep(0.1)
    ~~~~~~~~~~^^^^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/arbiter.py", line 241, in handle_chld
    self.reap_workers()
    ~~~~~~~~~~~~~~~~~^^
  File "/home/kalicat/Desktop/inventory_website/venv_inventory-web/lib/python3.13/site-packages/gunicorn/arbiter.py", line 529, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
